### ISSUE TITLE
[FEATURE] Make server function optional

### ISSUE THREAD

**Issue by domrim** [kbrebanov/ansible-openldap#1]
Hi,
i'm using the role to config all of our Clients in the Network.
So i had the idea to make the server function of the role optional with a variable.
For example "ldap_server" which could be set true or false.
I started implementing the function in a fork and would push it if you agree.
Greets Dominik

**Comment by kbrebanov** [comment]
@domrim Sure. Create a PR for it.

**Comment by ozbillwang** [comment]
+1

we do need two roles for open-ldap server and role for open-ldap client.

**Comment by kbrebanov** [comment]
This Ansible role is no longer being maintained.
