### ISSUE TITLE
Multiple runs restart slapd everytime

### ISSUE THREAD

**Issue by ShortyFR** [kbrebanov/ansible-openldap#3]
It seems that when you run this role several times, the password configuration is reset everythime (a new hash value is calculated in "Hash OpenLDAP rootpw" and therefore slapd is restarted.

I would expect that running the role multiple times would not do anything unless a variable is changed.

**Comment by ShortyFR** [comment]
I forgot to mention I tested this on Ubuntu 16.04.

**Comment by kbrebanov** [comment]
This Ansible role is no longer being maintained.
